openapi: 3.0.3
info:
  title: Task Management - Projects API
  version: 1.0.0
  description: Project management endpoints for CRUD operations, team management, and invitations

servers:
  - url: https://api.taskmanagement.local/api/v1
  - url: https://api.taskmanagement.app/api/v1

paths:
  /projects:
    get:
      summary: Get all projects for current user
      operationId: getProjects
      tags: [Projects]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectSummary'
    
    post:
      summary: Create new project
      operationId: createProject
      tags: [Projects]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name]
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                description:
                  type: string
                  maxLength: 1000
                  nullable: true
      responses:
        '201':
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetail'

  /projects/{projectId}:
    get:
      summary: Get project details
      operationId: getProject
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      responses:
        '200':
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetail'
        '404':
          $ref: '#/components/responses/NotFound'
    
    put:
      summary: Update project (Owner/Manager only)
      operationId: updateProject
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                description:
                  type: string
                  maxLength: 1000
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetail'
        '403':
          $ref: '#/components/responses/Forbidden'
    
    delete:
      summary: Delete project (Owner only)
      operationId: deleteProject
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      responses:
        '204':
          description: Project deleted
        '403':
          $ref: '#/components/responses/Forbidden'

  /projects/{projectId}/members:
    get:
      summary: Get project team members
      operationId: getProjectMembers
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      responses:
        '200':
          description: List of team members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectMember'

  /projects/{projectId}/members/{userId}:
    delete:
      summary: Remove member from project (Owner/Manager only)
      operationId: removeMember
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProjectId'
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Member removed
        '403':
          $ref: '#/components/responses/Forbidden'

  /projects/{projectId}/invitations:
    post:
      summary: Invite user to project (Owner/Manager only)
      operationId: inviteMember
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ProjectId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, role]
              properties:
                email:
                  type: string
                  format: email
                role:
                  type: string
                  enum: [Manager, Member]
      responses:
        '201':
          description: Invitation sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectInvitation'

  /invitations/{token}/accept:
    post:
      summary: Accept project invitation
      operationId: acceptInvitation
      tags: [Projects]
      security:
        - bearerAuth: []
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Invitation accepted, user added to project
        '404':
          description: Invitation not found or expired

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ProjectId:
      name: projectId
      in: path
      required: true
      schema:
        type: integer
      description: Project unique identifier

  schemas:
    ProjectSummary:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        role:
          type: string
          enum: [Owner, Manager, Member]
        memberCount:
          type: integer
        taskCount:
          type: integer
        createdAt:
          type: string
          format: date-time

    ProjectDetail:
      allOf:
        - $ref: '#/components/schemas/ProjectSummary'
        - type: object
          properties:
            owner:
              $ref: '#/components/schemas/UserSummary'
            members:
              type: array
              items:
                $ref: '#/components/schemas/ProjectMember'

    ProjectMember:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        fullName:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [Owner, Manager, Member]
        joinedAt:
          type: string
          format: date-time

    ProjectInvitation:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        role:
          type: string
          enum: [Manager, Member]
        status:
          type: string
          enum: [Pending, Accepted, Declined, Expired]
        invitedBy:
          $ref: '#/components/schemas/UserSummary'
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

    UserSummary:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        fullName:
          type: string
        email:
          type: string
        profilePictureUrl:
          type: string
          nullable: true

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              correlationId:
                type: string

    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              correlationId:
                type: string
